export interface MockCase {
  id: string
  case_number: string
  case_title: string
  court: string
  date_filed: string
  department: string
  status: "pending_review" | "verified" | "escalated" | "in_review" | "processing"
  priority: "high" | "medium" | "low" | "critical"
  assigned_officer: string
  deadline: string
  action_summary: string
  compliance_actions: string[]
  pdf_filename: string
  pdf_url: string
  created_at: string
}

export const MOCK_CASES: MockCase[] = [
  {
    id: "mc-001",
    case_number: "WP(C) 4821/2024",
    case_title: "State of Maharashtra vs. Municipal Corp. Nashik",
    court: "Bombay High Court",
    date_filed: "2024-03-12",
    department: "Revenue",
    status: "pending_review",
    priority: "critical",
    assigned_officer: "Adv. Priya Mehta",
    deadline: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    action_summary: "Municipality directed to refund excess property tax collected between 2019-2023. Comptroller audit required within 45 days.",
    compliance_actions: [
      "Conduct Comptroller audit of property tax records 2019–2023",
      "Publish refund schedule in official gazette",
      "Submit compliance report to HC within 45 days",
    ],
    pdf_filename: "WP4821_2024_judgment.pdf",
    pdf_url: "#",
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "mc-002",
    case_number: "CWP 11203/2024",
    case_title: "Sharma & Ors vs. NHAI",
    court: "Punjab & Haryana High Court",
    date_filed: "2024-02-28",
    department: "PWD",
    status: "verified",
    priority: "high",
    assigned_officer: "Sr. Eng. Ranjit Kumar",
    deadline: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    action_summary: "NHAI ordered to complete compensation disbursement for land acquisition in Sector 17 bypass project within 30 days.",
    compliance_actions: [
      "Process land acquisition compensation for 34 families",
      "File utilization certificate with District Collector",
      "Submit completion report to HC Registrar",
    ],
    pdf_filename: "CWP11203_NHAI.pdf",
    pdf_url: "#",
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "mc-003",
    case_number: "OA 765/2024",
    case_title: "Dr. Kavya Nair vs. AIIMS Delhi",
    court: "Central Administrative Tribunal",
    date_filed: "2024-01-15",
    department: "Health",
    status: "escalated",
    priority: "high",
    assigned_officer: "DHS Secretary",
    deadline: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    action_summary: "CAT directs AIIMS to reinstate Dr. Nair with full back-pay within 60 days of order. Non-compliance attracts contempt proceedings.",
    compliance_actions: [
      "Issue reinstatement order with effect from 15 Jan 2024",
      "Calculate and disburse back-pay arrears",
      "Furnish compliance affidavit to CAT Registrar",
    ],
    pdf_filename: "OA765_AIIMS.pdf",
    pdf_url: "#",
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "mc-004",
    case_number: "SLP(C) 9934/2024",
    case_title: "Greenland Developers vs. State of Rajasthan",
    court: "Supreme Court of India",
    date_filed: "2024-04-01",
    department: "Revenue",
    status: "in_review",
    priority: "medium",
    assigned_officer: "Adv. Sunita Rao",
    deadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    action_summary: "SC stays demolition of disputed structures and directs state to maintain status quo. Survey report by commissioner required in 6 weeks.",
    compliance_actions: [
      "Halt all demolition activities in survey zone",
      "Appoint independent survey commissioner",
      "Submit geo-tagged survey report to SC within 42 days",
    ],
    pdf_filename: "SLP9934_Greenland.pdf",
    pdf_url: "#",
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "mc-005",
    case_number: "WA 2271/2023",
    case_title: "Fishermen Welfare Association vs. Kerala Govt.",
    court: "Kerala High Court",
    date_filed: "2023-11-20",
    department: "Agriculture",
    status: "verified",
    priority: "low",
    assigned_officer: "Mr. Thomas Varghese",
    deadline: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString(),
    action_summary: "State directed to implement modified trawling ban schedule with 15-day relief periods. Welfare fund disbursement to be completed by March 2025.",
    compliance_actions: [
      "Notify revised trawling schedule in Official Gazette",
      "Disburse Rs. 5,000 relief to registered fishermen",
      "Set up grievance committee in coastal districts",
    ],
    pdf_filename: "WA2271_Fishermen.pdf",
    pdf_url: "#",
    created_at: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "mc-006",
    case_number: "MA 4512/2024",
    case_title: "Green Earth NGO vs. Pollution Control Board",
    court: "National Green Tribunal",
    date_filed: "2024-03-30",
    department: "Environment",
    status: "pending_review",
    priority: "high",
    assigned_officer: "Dr. Anjali Desai",
    deadline: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    action_summary: "NGT orders immediate closure of 12 industrial units exceeding effluent discharge norms. State PCB to submit action-taken report in 30 days.",
    compliance_actions: [
      "Issue closure notices to 12 identified industrial units",
      "Deploy inspection teams for effluent sampling",
      "Submit action-taken report to NGT with photographic evidence",
    ],
    pdf_filename: "MA4512_GreenEarth.pdf",
    pdf_url: "#",
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "mc-007",
    case_number: "CPC 883/2023",
    case_title: "Teachers Federation vs. State of UP",
    court: "Allahabad High Court",
    date_filed: "2023-09-10",
    department: "Education",
    status: "verified",
    priority: "medium",
    assigned_officer: "Adv. Ramesh Pandey",
    deadline: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000).toISOString(),
    action_summary: "HC orders regularization of 8,400 contract teachers with seniority benefits. Pay revision to be effected within 90 days of judgment.",
    compliance_actions: [
      "Prepare regularization list of eligible 8,400 teachers",
      "Issue appointment letters with revised pay scale",
      "Publish seniority list in district education portals",
    ],
    pdf_filename: "CPC883_Teachers.pdf",
    pdf_url: "#",
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "mc-008",
    case_number: "WP 6644/2024",
    case_title: "Vijay Kumar vs. State Bank of India",
    court: "Delhi High Court",
    date_filed: "2024-04-10",
    department: "Finance",
    status: "processing",
    priority: "low",
    assigned_officer: "Pending Assignment",
    deadline: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString(),
    action_summary: "HC directs SBI to restore petitioner's account and reverse wrongful charges. Bank to comply within 15 working days.",
    compliance_actions: [
      "Restore deactivated account WP/6644/VK",
      "Reverse transaction charges of Rs. 24,500",
      "Issue written apology and NOC certificate",
    ],
    pdf_filename: "WP6644_SBI.pdf",
    pdf_url: "#",
    created_at: new Date(Date.now() - 0.5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "mc-009",
    case_number: "OWP 3312/2024",
    case_title: "Digital Rights Foundation vs. CERT-In",
    court: "Delhi High Court",
    date_filed: "2024-04-05",
    department: "IT",
    status: "in_review",
    priority: "medium",
    assigned_officer: "Adv. Meera Pillai",
    deadline: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000).toISOString(),
    action_summary: "HC stays CERT-In directive requiring VPN providers to log user data for 5 years pending further hearing. CERT-In to file reply affidavit.",
    compliance_actions: [
      "File reply affidavit before HC within 3 weeks",
      "Submit policy review documentation",
      "Coordinate with MeitY for interim compliance framework",
    ],
    pdf_filename: "OWP3312_DRF.pdf",
    pdf_url: "#",
    created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "mc-010",
    case_number: "LA 1102/2024",
    case_title: "Hemant Singh vs. Uttarakhand Transport Corp.",
    court: "Uttarakhand High Court",
    date_filed: "2024-02-14",
    department: "Transport",
    status: "pending_review",
    priority: "medium",
    assigned_officer: "RTO Commissioner",
    deadline: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    action_summary: "HC directs UTC to pay motor accident compensation of Rs. 18.5 lakh to petitioner within 8 weeks. Insurance claim to be processed simultaneously.",
    compliance_actions: [
      "Process insurance claim through SBI General Insurance",
      "Prepare compensation payment order",
      "Submit payment proof affidavit to HC within 56 days",
    ],
    pdf_filename: "LA1102_UTC.pdf",
    pdf_url: "#",
    created_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

export const DEPARTMENTS = ["Revenue", "PWD", "Health", "Environment", "Education", "Finance", "IT", "Transport", "Agriculture"]
export const COURTS = ["Supreme Court of India", "Bombay High Court", "Delhi High Court", "Allahabad High Court", "Kerala High Court", "Punjab & Haryana High Court", "Central Administrative Tribunal", "National Green Tribunal", "Uttarakhand High Court"]
